name: Slack Notifications

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp
        run: |
          echo "TIMESTAMP=$(date +%s -d "${{ github.event.release.published_at }}")" >> $GITHUB_ENV
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: wearerequired/slack-messaging-action@v1
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: >-
            {
              "attachments": [
                {
                  "fallback": "${{ github.event.repository.name }} has been updated.",
                  "color": "#00cccc",
                  "pretext": "A new release for ${{ github.event.repository.name }} was published on Github!",
                  "title": "${{ github.event.repository.name }} - ${{ github.event.release.tag_name }}",
                  "title_link": "${{ github.event.release.html_url }}",
                  "text": "${{ github.event.release.body }}",
                  "footer": "PackBot",
                  "footer_icon": "https://cribl.io/favicon.ico",
                  "ts": ${{ env.TIMESTAMP }}
                }
              ]
            }